export enum RtcCallState {
  IDLE = "IDLE",
  DIALING = "DIALING",
  RECEIVING_CALL = "RECEIVING_CALL",
  OUTGOING_CALL_REJECTED = "OUTGOING_CALL_REJECTED",
  INCOMMING_CALL_REJECTED = "INCOMMING_CALL_REJECTED",
  OUTGOING_CALL_CONNECTED = "OUTGOING_CALL_CONNECTED",
  INCOMMING_CALL_CONNECTED = "INCOMMING_CALL_CONNECTED",
  OUTGOING_CALL_COMPLETED = "OUTGOING_CALL_COMPLETED",
  INCOMMING_CALL_COMPLETED = "INCOMMING_CALL_COMPLETED"
}
