export enum RtcCallState {
  NONE = "NONE",
  DIALING = "DIALING",
  RECEIVING_CALL = "RECEIVING_CALL",
  ACCEPTED = "ACCEPTED",
  MISSED_CALL = "MISSED_CALL",
  CALL_NOT_ANSWERED = "CALL_NOT_ANSWERED",
  OUTGOING_CALL_REJECTED = "OUTGOING_CALL_REJECTED",
  INCOMING_CALL_REJECTED = "INCOMING_CALL_REJECTED",
  OUTGOING_CALL_CONNECTED = "OUTGOING_CALL_CONNECTED",
  INCOMING_CALL_CONNECTED = "INCOMING_CALL_CONNECTED",
  OUTGOING_CALL_COMPLETED = "OUTGOING_CALL_COMPLETED",
  INCOMING_CALL_COMPLETED = "INCOMING_CALL_COMPLETED"
}
